AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'lib/castle/core_ext/hash/keys.rb'

Style/FileName:
  Exclude:
    - "lib/castle-rb.rb"

Style/MethodMissing:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 100

RSpec/NestedGroups:
  Max: 4
