language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: ruby-head

