dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

before_install:
  - gem install bundler
  - gem update --system

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  slack:
    secure: JVXUf9/+m3mRZU6WnJxgskpSbDY6tHRTQwFeUtq7eYFdXYr/BTCprS2RsANLr8K5eLBgOJeEILAZW/plwpBfa9TnWQxknL/OqY4nyrrtUdc+i7TfBNEwO/I6owvELKSYjgxjClJXkcPS8pg6UTr+wYpbQ+7ToVnPdHf6J3Hy7X4=
    on_success: change
    on_failure: always

script: bundle exec rspec
